import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000';
const examples=[
'The streetlight near our college gate has been broken for three days and the road becomes very dark at night.',
'There is a large pothole near the main bus stop causing traffic problems.',
'Garbage has been accumulating beside the community park for several days.'
];
function App(){
 const [text,setText]=useState(''),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState('');
 async function analyze(e){e.preventDefault();setError('');setResult(null);if(text.trim().length<10){setError('Please describe the issue in at least 10 characters.');return}setLoading(true);try{const r=await fetch(`${API}/api/analyze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({complaint:text})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');setResult(d)}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <div className="page"><nav><b><i>C</i>CivicFix AI</b><small>HACKDEVENGERS 1.0</small></nav><main><section className="hero"><label>AI-POWERED COMMUNITY ACTION</label><h1>Turn complaints into <span>clear action.</span></h1><p>Describe a local issue in plain language. CivicFix AI structures it, estimates urgency, and recommends where it should go next.</p></section><section className="grid"><article className="card"><label>01 / REPORT</label><h2>What is happening?</h2><form onSubmit={analyze}><textarea value={text} onChange={e=>setText(e.target.value)} maxLength="2000" placeholder="Example: The streetlight outside the college gate has been broken for three days..."/><div className="row"><small>{text.length}/2000</small><button disabled={loading}>{loading?'Analyzing...':'Analyze Issue →'}</button></div></form><p className="try">Try an example</p>{examples.map(x=><button className="example" onClick={()=>setText(x)} key={x}>{x}</button>)}</article><article className="card"><label>02 / DECISION</label><h2>Structured result</h2>{loading&&<div className="empty"><div className="loader"/><h3>Understanding the issue...</h3><p>Classifying the report and preparing a practical action plan.</p></div>}{!loading&&!result&&<div className="empty"><div className="star">✦</div><h3>Your result will appear here</h3><p>Submit a community issue to see category, urgency, action and routing.</p></div>}{result&&<div className="result"><div className="top"><div><label>CATEGORY</label><strong>{result.category}</strong></div><em className={result.urgency.toLowerCase()}>{result.urgency}</em></div><div className="box"><label>SUMMARY</label><p>{result.summary}</p></div><div className="tw"><div><label>RECOMMENDED ACTION</label><p>{result.recommended_action}</p></div><div><label>RESPONSIBLE DEPARTMENT</label><p>{result.department}</p></div></div><label>TAGS</label><div className="tags">{result.tags.map(t=><span key={t}>#{t}</span>)}</div><small className="source">{result.ai_generated?'Gemini AI analysis':'Deterministic fallback analysis'}</small></div>}{error&&<div className="error">{error}</div>}</article></section><section className="steps"><div><b>01</b><h3>Describe</h3><p>Write the issue naturally.</p></div><div><b>02</b><h3>Understand</h3><p>AI structures the report.</p></div><div><b>03</b><h3>Act</h3><p>Use priority and routing to act.</p></div></section></main><footer>CivicFix AI · HackDevengers 1.0 · Prototype</footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
const API_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";